name: V8 Upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day

jobs:
    upgrade:
        name: Upgrade V8
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: true
                fetch-depth: 0
            - uses: actions/setup-python@v4
              with:
                python-version: '3.8'
            - run: cd deps/depot_tools && git config --unset-all remote.origin.fetch; git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
              shell: bash
            - run: echo "$PWD/deps/depot_tools" >> $GITHUB_PATH
              shell: bash
            - run: cd deps && python upgrade_v8.py
            - id: pr_metadata
              run: |
                echo "pr_branch=v8_$(cat deps/v8_version)_upgrade" >> $GITHUB_OUTPUT
                echo "pr_commit_message=Upgrade V8 binaries for $(cat deps/v8_version) version" >> $GITHUB_OUTPUT
                echo "pr_body=Auto-generated pull request to upgrade V8 binary for $(cat deps/v8_version) version" >> $GITHUB_OUTPUT
            - uses: peter-evans/create-pull-request@v4
              with:
                commit-message: ${{steps.pr_metadata.outputs.pr_commit_message}}
                branch: ${{steps.pr_metadata.outputs.pr_branch}}
                delete-branch: true
                title: ${{steps.pr_metadata.outputs.pr_commit_message}}
                body: ${{steps.pr_metadata.outputs.pr_body}}
